:lang: ja
:doctype: book
:toc-title: 目次
:toc: left
:sectnums:
:docname: = Asciidoc
:author: やまもとじゅん
:revnumber: 0.1
:revdate: 2018/12/16

= Asciidoc

[.lead]
AsciiDocは軽量マークアップ言語のひとつである。AsciiDocは2002年、Stuart Rackhamによって構想された。

== 特徴
* ビルドする環境を整えるのが（比較的）楽
* GitHub で利用できる（Pagesではレンダリングできないけど）

== 書き方
=== 骨組み
==== Document Types
article::
短い文書、記事、一般的な文書に使用されます。
book::
脚注、目次、表のリスト、図表のリスト、例と索引のリストを自動的に生成することができる
manpage::
roff形式のUNIXマニュアルページの生成に使用
----
:doctype: article
:doctype: book
:doctype: manpage
----

==== セクションに番号を振る
----
:sectnums:
----

==== 見出しから目次を自動で作る
----
:toc:
:toc: left (左側に表示)
:toc-title: 目次 (目次のタイトルを指定)
----
NOTE: ToCとはTable of Contentsの略。

[[anchor-name]]
==== アンカー
見出しを作成すると自動的に付加される。
----
=== アンカー (-> id="_アンカー")
----

===== 任意のアンカーを振る
[[任意のアンカー]]この文章にはアンカーを振っています
----
[[任意のアンカー]]この文章にはアンカーを振っています

[[anchor-name]]
=== アンカー (-> id="anchor-name")
----

=== 段落
新しい段落を始める時は、最低１行の空白行を入れる

==== 改行
===== +
----
ルビーの色は赤です。 +
トパーズの色は青です。
----
ルビーの色は赤です。 +
トパーズの色は青です。

===== hardbreaks
----
[%hardbreaks]
ルビーの色は赤です。
トパーズの色は青です。
----
[%hardbreaks]
ルビーの色は赤です。
トパーズの色は青です。

==== リテラル
----
リテラル

  １つ以上の空白で始まる連続した行はリテラル段落とみなされます。
----
リテラル

  １つ以上の空白で始まる連続した行はリテラル段落とみなされます。

==== 注釈
----
NOTE: 脚注段落は補足情報を示すものです。

TIP: チップスを記述します。

IMPORTANT: 重要事項を記述します。

WARNING: 警告を記述します。

CAUTION: 注意を記述します。
----

NOTE: 脚注段落は補足情報を示すものです。

TIP: チップスを記述します。

IMPORTANT: 重要事項を記述します。

WARNING: 警告を記述します。

CAUTION: 注意を記述します。

==== リード文
----
[.lead]
章のリードが必要ならここに書く。
----
[.lead]
章のリードが必要ならここに書く。

=== テーブル
==== CSV
----
[format="csv", options="header"]
|===
-, A, B
1, A-1, B-1
2, A-2, B-2
|===
----
[format="csv", options="header"]
|===
-, A, B
1, A-1, B-1
2, A-2, B-2
|===

== HTMLに変換する
asciidoctor:: asciidocファイルをHTMLファイルに変換するruby製ツール
----
gem install asciidoctor
----

== PDFに変換する
asciidoctor-pdf ::
asciidocファイルをPDFファイルに変換するruby製ツール
asciidoctor-pdf-cjk::
日本語を使った文章向けの設定

----
gem install --pre asciidoctor-pdf
gem install asciidoctor-pdf-cjk
----

----
asciidoctor-pdf -r asciidoctor-pdf-cjk ./Asciidoc.asciidoc -o docs/pdf/Asciidoc.pd
----

== Atom での AsciiDoc
=== パッケージ
* asciidoc-preview
* language-asciidoc

== 参考資料
* https://qiita.com/ponsuke0531/items/302638ad6fbed05d97fc[日語があるAsciiDocのファイルをPDFにする方法]
* https://qiita.com/gho4d76g/items/302e1ff91754b9b50f34#%E3%81%AA%E3%81%9Casciidoc[asciidoctor-pdfで社内ドキュメントを書こう]
